### ISSUE TITLE
Customise Table without default `isolevel`

### ISSUE THREAD

**Issue by sheruost** [VermiIIi0n/async-tinydb#12]
I've managed to build a dedicated user database with customised BaseID, BaseDocument and TinyDB preset to `isolevel=2`.
However I noticed that the `isolevel` of Table is always set to `0` in __init__(). Is there any reason to keep user away from doing so?

To clarify, I know you can inherit isolevel from TinyDB instance by calling `self.table()`, but my scenario is that I'm splitting CRUD per Table, hence I would like to inherit Table directly into my customised Table class. (e.g. `class UserTable(Table)`)

**Comment by VermiIIi0n** [comment]
Ah, sorry for the late reply, I forgot to watch this repo and missed the email for this issue.

Because of the way tables are created, the default value of `isolevel` is actually specified in  `TinyDB` class. `0` is just a dummy initialising value, modifying it won't make any difference.

For simplicity I decided to make `isolevel` the same across all tables. If you tables are accessing overlapping data, using mixed `isolevel` may lead to data corruption, otherwise it should be fine to do so.
